# Generated by Django 3.0.4 on 2020-05-14 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='name',
            new_name='password',
        ),
    ]
