# Generated by Django 3.0.4 on 2020-05-14 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_newprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='newprofile',
            name='profilepicture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
