# Generated by Django 3.0.4 on 2020-05-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_newprofile_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='images/uploads/')),
            ],
        ),
    ]
