# Generated by Django 3.0.4 on 2020-05-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='newprofile',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='newprofile',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
