# Generated by Django 3.0.4 on 2020-05-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20200515_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='caption',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
