# Generated by Django 3.0.4 on 2020-05-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_pictures_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='newprofile',
            name='followers',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
