# Generated by Django 3.0.4 on 2020-05-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_newprofile_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newprofile',
            name='followers',
            field=models.IntegerField(default=0),
        ),
    ]
