# Generated by Django 3.0.4 on 2020-05-17 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200517_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='newprofile',
            name='followersName',
            field=models.TextField(default=''),
        ),
    ]
