# Generated by Django 3.0.4 on 2020-05-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_newprofile_followersname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newprofile',
            old_name='followersName',
            new_name='followerNames',
        ),
    ]
