# Generated by Django 3.0.4 on 2020-05-18 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20200517_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='newprofile',
            name='following',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='newprofile',
            name='followingNames',
            field=models.TextField(default=''),
        ),
    ]
