# Generated by Django 3.0.4 on 2020-05-19 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_auto_20200518_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='newprofile',
            name='notifications',
            field=models.TextField(default=''),
        ),
    ]
